using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Groz_Backend.Migrations
{
    /// <inheritdoc />
    public partial class AppGuidRevenueCatAndAppleSearchAdsIds : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<long>(
                name: "AppleSearchAdsId",
                table: "Apps",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "RevenueCatId",
                table: "Apps",
                type: "text",
                nullable: false,
                defaultValue: "");

            // PostgreSQL cannot ALTER an identity bigint column to uuid; replace the key column.
            migrationBuilder.Sql(
                """
                ALTER TABLE "Apps" ADD COLUMN "Id_new" uuid NOT NULL DEFAULT gen_random_uuid();
                ALTER TABLE "Apps" DROP CONSTRAINT "PK_Apps";
                ALTER TABLE "Apps" DROP COLUMN "Id";
                ALTER TABLE "Apps" RENAME COLUMN "Id_new" TO "Id";
                ALTER TABLE "Apps" ADD CONSTRAINT "PK_Apps" PRIMARY KEY ("Id");
                ALTER TABLE "Apps" ALTER COLUMN "Id" SET DEFAULT gen_random_uuid();
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AppleSearchAdsId",
                table: "Apps");

            migrationBuilder.DropColumn(
                name: "RevenueCatId",
                table: "Apps");

            migrationBuilder.Sql(
                """
                ALTER TABLE "Apps" ADD COLUMN "Id_new" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
                ALTER TABLE "Apps" DROP CONSTRAINT "PK_Apps";
                ALTER TABLE "Apps" DROP COLUMN "Id";
                ALTER TABLE "Apps" RENAME COLUMN "Id_new" TO "Id";
                ALTER TABLE "Apps" ADD CONSTRAINT "PK_Apps" PRIMARY KEY ("Id");
                """);
        }
    }
}
